version: '3'
services:
  pdp:
    build: ./pdp  # Dockerfile path for PDP service
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080

  pep:
    build: ./pep  # Dockerfile path for PEP service
    ports:
      - "8081:8080"  # Map container port 8080 to host port 8081
    depends_on:
      - pdp  # Ensure PEP waits for PDP to be ready before starting

  pap:
    build: ./pap  # Dockerfile path for PAP service
    ports:
      - "8082:8080"  # Map container port 8080 to host port 8082

  pip:
    build: ./pip  # Dockerfile path for PIP service
    ports:
      - "8083:8080"  # Map container port 8080 to host port 8083
